/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminsRouteImport } from './routes/admins'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IntegrationRouteImport } from './routes/integration'
import { Route as ScreenRouteImport } from './routes/screen'
import { Route as ScreensRouteImport } from './routes/screens'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as WaitersRouteImport } from './routes/waiters'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsRoute = AdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationRoute = IntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenRoute = ScreenRouteImport.update({
  id: '/screen',
  path: '/screen',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreensRoute = ScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitersRoute = WaitersRouteImport.update({
  id: '/waiters',
  path: '/waiters',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/history': typeof HistoryRoute
  '/integration': typeof IntegrationRoute
  '/screen': typeof ScreenRoute
  '/screens': typeof ScreensRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/waiters': typeof WaitersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/history': typeof HistoryRoute
  '/integration': typeof IntegrationRoute
  '/screen': typeof ScreenRoute
  '/screens': typeof ScreensRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/waiters': typeof WaitersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/history': typeof HistoryRoute
  '/integration': typeof IntegrationRoute
  '/screen': typeof ScreenRoute
  '/screens': typeof ScreensRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/waiters': typeof WaitersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admins'
    | '/auth'
    | '/demo'
    | '/history'
    | '/integration'
    | '/screen'
    | '/screens'
    | '/settings'
    | '/stats'
    | '/waiters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admins'
    | '/auth'
    | '/demo'
    | '/history'
    | '/integration'
    | '/screen'
    | '/screens'
    | '/settings'
    | '/stats'
    | '/waiters'
  id:
    | '__root__'
    | '/'
    | '/admins'
    | '/auth'
    | '/demo'
    | '/history'
    | '/integration'
    | '/screen'
    | '/screens'
    | '/settings'
    | '/stats'
    | '/waiters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminsRoute: typeof AdminsRoute
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
  HistoryRoute: typeof HistoryRoute
  IntegrationRoute: typeof IntegrationRoute
  ScreenRoute: typeof ScreenRoute
  ScreensRoute: typeof ScreensRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  WaitersRoute: typeof WaitersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins': {
      id: '/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration': {
      id: '/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof IntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen': {
      id: '/screen'
      path: '/screen'
      fullPath: '/screen'
      preLoaderRoute: typeof ScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screens': {
      id: '/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof ScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiters': {
      id: '/waiters'
      path: '/waiters'
      fullPath: '/waiters'
      preLoaderRoute: typeof WaitersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminsRoute: AdminsRoute,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
  HistoryRoute: HistoryRoute,
  IntegrationRoute: IntegrationRoute,
  ScreenRoute: ScreenRoute,
  ScreensRoute: ScreensRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  WaitersRoute: WaitersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
